export const ALL_PATIENT_REQUEST = "ALL_PATIENT_REQUEST"
export const ALL_PATIENT_SUCCESS = "ALL_PATIENT_SUCCESS"
export const ALL_PATIENT_FAIL = "ALL_PATIENT_FAIL"

export const PATIENT_DETAILS_REQUEST="PATIENT_DETAILS_REQUEST"
export const PATIENT_DETAILS_SUCCESS ="PATIENT_DETAILS_SUCCESS"
export const PATIENT_DETAILS_FAIL="PATIENT_DETAILS_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"